name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-service:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push notifier
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./FortniteNotifier/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fortnite-notifier:latest
          
  build-admin:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push admin
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./FortniteNotifier.Admin/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fortnite-notifier-admin:latest
